package com.example.Student_Library_Management_System.Service;

import com.example.Student_Library_Management_System.Enums.CardStatus;
import com.example.Student_Library_Management_System.Models.Card;
import com.example.Student_Library_Management_System.Models.Student;
import com.example.Student_Library_Management_System.Repository.StudentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class StudentService {
    @Autowired
    StudentRepository studentRepository;

    public String addStudent(Student student) {
        //basic attributes of student is set by user, in postman

        //cardStatus of card entity is not set
        //card should also be autogenerated when addStudent() is called
        Card card = new Card();
        card.setCardStatus(CardStatus.ACTIVATED); //set enums -> activated

        //Student in card entity is not set
        card.setStudent(student);                 //to establish which card belongs to which student
                                                  //id of this student -> set as foreign key in this card

        //Card in student entity is not set
        student.setCard(card);

        //if it were unidirectional mapping -> had to save both parent and child class
        //since we are using bidirectional, we need not save child class, as its auto saved -> cascading effect
        studentRepository.save(student);

        return "Student and card added";
    }

}
